name: Update Instagram Followers Count

on:
  # Exécute l'action toutes les 6 heures (ou selon votre choix)
  schedule:
    - cron: '0 */6 * * *'
  # Permet de lancer l'action manuellement
  workflow_dispatch: 

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    # Correction des Permissions : Nécessaire pour que l'Action puisse commiter
    permissions:
      contents: write 
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies (Instaloader)
      run: |
        python -m pip install --upgrade pip
        pip install instaloader

    - name: Execute Python script
      # Transmet les secrets d'authentification
      env:
        INSTA_USERNAME: ${{ secrets.INSTA_USERNAME }}
        INSTA_PASSWORD: ${{ secrets.INSTA_PASSWORD }}
      run: python fetch_followers.py 

    - name: Commit and Push new data
      # Correction de l'erreur: remplacement de 'files' par 'file_pattern'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'ACTION: Auto-update Instagram followers count'
        file_pattern: 'fils/followers_data.json' # Ligne Corrigée
